/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUnidadesRouteImport } from './routes/_authenticated/unidades'
import { Route as AuthenticatedProfissionaisRouteImport } from './routes/_authenticated/profissionais'
import { Route as AuthenticatedNoShowRouteImport } from './routes/_authenticated/no-show'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedHeatmapRouteImport } from './routes/_authenticated/heatmap'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfigRouteImport } from './routes/_authenticated/config'
import { Route as AuthenticatedAnalyticsRentabilidadeRouteImport } from './routes/_authenticated/analytics/rentabilidade'
import { Route as AuthenticatedAnalyticsPrevisoesRouteImport } from './routes/_authenticated/analytics/previsoes'
import { Route as AuthenticatedAnalyticsComercialRouteImport } from './routes/_authenticated/analytics/comercial'
import { Route as AuthenticatedAnalyticsCapacidadeRouteImport } from './routes/_authenticated/analytics/capacidade'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUnidadesRoute = AuthenticatedUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfissionaisRoute =
  AuthenticatedProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNoShowRoute = AuthenticatedNoShowRouteImport.update({
  id: '/no-show',
  path: '/no-show',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHeatmapRoute = AuthenticatedHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfigRoute = AuthenticatedConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRentabilidadeRoute =
  AuthenticatedAnalyticsRentabilidadeRouteImport.update({
    id: '/analytics/rentabilidade',
    path: '/analytics/rentabilidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsPrevisoesRoute =
  AuthenticatedAnalyticsPrevisoesRouteImport.update({
    id: '/analytics/previsoes',
    path: '/analytics/previsoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsComercialRoute =
  AuthenticatedAnalyticsComercialRouteImport.update({
    id: '/analytics/comercial',
    path: '/analytics/comercial',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsCapacidadeRoute =
  AuthenticatedAnalyticsCapacidadeRouteImport.update({
    id: '/analytics/capacidade',
    path: '/analytics/capacidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/config': typeof AuthenticatedConfigRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/heatmap': typeof AuthenticatedHeatmapRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/no-show': typeof AuthenticatedNoShowRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/analytics/capacidade': typeof AuthenticatedAnalyticsCapacidadeRoute
  '/analytics/comercial': typeof AuthenticatedAnalyticsComercialRoute
  '/analytics/previsoes': typeof AuthenticatedAnalyticsPrevisoesRoute
  '/analytics/rentabilidade': typeof AuthenticatedAnalyticsRentabilidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/config': typeof AuthenticatedConfigRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/heatmap': typeof AuthenticatedHeatmapRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/no-show': typeof AuthenticatedNoShowRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/unidades': typeof AuthenticatedUnidadesRoute
  '/analytics/capacidade': typeof AuthenticatedAnalyticsCapacidadeRoute
  '/analytics/comercial': typeof AuthenticatedAnalyticsComercialRoute
  '/analytics/previsoes': typeof AuthenticatedAnalyticsPrevisoesRoute
  '/analytics/rentabilidade': typeof AuthenticatedAnalyticsRentabilidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/config': typeof AuthenticatedConfigRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/heatmap': typeof AuthenticatedHeatmapRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/no-show': typeof AuthenticatedNoShowRoute
  '/_authenticated/profissionais': typeof AuthenticatedProfissionaisRoute
  '/_authenticated/unidades': typeof AuthenticatedUnidadesRoute
  '/_authenticated/analytics/capacidade': typeof AuthenticatedAnalyticsCapacidadeRoute
  '/_authenticated/analytics/comercial': typeof AuthenticatedAnalyticsComercialRoute
  '/_authenticated/analytics/previsoes': typeof AuthenticatedAnalyticsPrevisoesRoute
  '/_authenticated/analytics/rentabilidade': typeof AuthenticatedAnalyticsRentabilidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/config'
    | '/dashboard'
    | '/financeiro'
    | '/heatmap'
    | '/mapa'
    | '/no-show'
    | '/profissionais'
    | '/unidades'
    | '/analytics/capacidade'
    | '/analytics/comercial'
    | '/analytics/previsoes'
    | '/analytics/rentabilidade'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/config'
    | '/dashboard'
    | '/financeiro'
    | '/heatmap'
    | '/mapa'
    | '/no-show'
    | '/profissionais'
    | '/unidades'
    | '/analytics/capacidade'
    | '/analytics/comercial'
    | '/analytics/previsoes'
    | '/analytics/rentabilidade'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/config'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/heatmap'
    | '/_authenticated/mapa'
    | '/_authenticated/no-show'
    | '/_authenticated/profissionais'
    | '/_authenticated/unidades'
    | '/_authenticated/analytics/capacidade'
    | '/_authenticated/analytics/comercial'
    | '/_authenticated/analytics/previsoes'
    | '/_authenticated/analytics/rentabilidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/unidades': {
      id: '/_authenticated/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof AuthenticatedUnidadesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profissionais': {
      id: '/_authenticated/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof AuthenticatedProfissionaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/no-show': {
      id: '/_authenticated/no-show'
      path: '/no-show'
      fullPath: '/no-show'
      preLoaderRoute: typeof AuthenticatedNoShowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/heatmap': {
      id: '/_authenticated/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof AuthenticatedHeatmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/config': {
      id: '/_authenticated/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthenticatedConfigRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/rentabilidade': {
      id: '/_authenticated/analytics/rentabilidade'
      path: '/analytics/rentabilidade'
      fullPath: '/analytics/rentabilidade'
      preLoaderRoute: typeof AuthenticatedAnalyticsRentabilidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/previsoes': {
      id: '/_authenticated/analytics/previsoes'
      path: '/analytics/previsoes'
      fullPath: '/analytics/previsoes'
      preLoaderRoute: typeof AuthenticatedAnalyticsPrevisoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/comercial': {
      id: '/_authenticated/analytics/comercial'
      path: '/analytics/comercial'
      fullPath: '/analytics/comercial'
      preLoaderRoute: typeof AuthenticatedAnalyticsComercialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/capacidade': {
      id: '/_authenticated/analytics/capacidade'
      path: '/analytics/capacidade'
      fullPath: '/analytics/capacidade'
      preLoaderRoute: typeof AuthenticatedAnalyticsCapacidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfigRoute: typeof AuthenticatedConfigRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedHeatmapRoute: typeof AuthenticatedHeatmapRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedNoShowRoute: typeof AuthenticatedNoShowRoute
  AuthenticatedProfissionaisRoute: typeof AuthenticatedProfissionaisRoute
  AuthenticatedUnidadesRoute: typeof AuthenticatedUnidadesRoute
  AuthenticatedAnalyticsCapacidadeRoute: typeof AuthenticatedAnalyticsCapacidadeRoute
  AuthenticatedAnalyticsComercialRoute: typeof AuthenticatedAnalyticsComercialRoute
  AuthenticatedAnalyticsPrevisoesRoute: typeof AuthenticatedAnalyticsPrevisoesRoute
  AuthenticatedAnalyticsRentabilidadeRoute: typeof AuthenticatedAnalyticsRentabilidadeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfigRoute: AuthenticatedConfigRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedHeatmapRoute: AuthenticatedHeatmapRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedNoShowRoute: AuthenticatedNoShowRoute,
  AuthenticatedProfissionaisRoute: AuthenticatedProfissionaisRoute,
  AuthenticatedUnidadesRoute: AuthenticatedUnidadesRoute,
  AuthenticatedAnalyticsCapacidadeRoute: AuthenticatedAnalyticsCapacidadeRoute,
  AuthenticatedAnalyticsComercialRoute: AuthenticatedAnalyticsComercialRoute,
  AuthenticatedAnalyticsPrevisoesRoute: AuthenticatedAnalyticsPrevisoesRoute,
  AuthenticatedAnalyticsRentabilidadeRoute:
    AuthenticatedAnalyticsRentabilidadeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
